export const AGENT_ROLES = ["DIRECTOR", "MANAGER", "SPECIALIST"];
export const SPECIALIST_ROLES = [
    "PROJECT_MANAGER",
    "TECH_LEAD",
    "SOFTWARE_ENGINEER",
    "QA_TESTER",
    "DEVOPS_ENGINEER",
    "CONTENT_AGENT",
    "MARKETING_AGENT",
    "FINANCE_AGENT",
    "CUSTOMER_SUPPORT_AGENT",
    "OPERATIONS_LOGISTICS_AGENT"
];
export const AGENT_STATES = ["IDLE", "MOVING", "WORKING", "MEETING", "BLOCKED"];
export const TASK_STATUSES = [
    "DRAFT",
    "QUEUED",
    "ASSIGNED",
    "IN_PROGRESS",
    "BLOCKED",
    "PENDING_APPROVAL",
    "DONE",
    "FAILED",
    "CANCELLED"
];
export const EXECUTION_MODES = ["REAL", "MOCK"];
export const APPROVAL_TYPES = ["EXTERNAL_ACTION", "HIGH_RISK_ACTION"];
export const WORKSPACE_ONBOARDING_STATES = [
    "WORKSPACE_SETUP",
    "SUBSCRIPTION_ACTIVE",
    "KNOWLEDGE_IMPORT",
    "INTEGRATIONS_CONNECTED",
    "AGENTS_HIRED",
    "PERMISSIONS_REVIEWED",
    "LAUNCHED"
];
export const WORKSPACE_SUBSCRIPTION_STATUSES = ["TRIALING", "ACTIVE", "PAST_DUE", "CANCELED"];
export const INTEGRATION_PROVIDERS = ["GITHUB", "LINKEDIN", "GMAIL"];
export const INTEGRATION_AUTH_STATUSES = ["DISCONNECTED", "CONNECTED", "ERROR"];
export const INTEGRATION_CAPABILITIES = ["READ", "WRITE", "POST", "SEND", "COMMIT", "PUSH"];
export const KNOWLEDGE_SOURCE_TYPES = ["FILE", "URL", "NOTE"];
